import { Menu } from '../../componets/molecules/menu/menu'
import './globals.css'
import { Dancing_Script } from 'next/font/google'

const fonts = Dancing_Script({ subsets: ['latin'] })

export const metadata = {
  title: 'Hotels ',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={fonts.className}>
        <Menu/>
        {children}</body>
    </html>
  )
}
