import { Menu } from '../../componets/molecules/menu/menu'
import './globals.css'
import { Dancing_Script, Inter } from 'next/font/google'
import { CurrentPageProvider } from './store/CurrentProvider'
import ProviderReservation from './store/ProvadierReservation'

const fonts = Dancing_Script({ subsets: ['latin'] })

export const metadata = {
  title: 'Hotels ',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <ProviderReservation>
        <CurrentPageProvider>
          <body className={fonts.className}>
           <Menu/>
             {children}
            </body>
        </CurrentPageProvider>
        </ProviderReservation>
    </html>
  )
}

